[[packages]]
name = "docker-ce"
version = "17.03.2~ce-0~ubuntu-xenial"
checkInstalledCmd = [
  "which docker"
]
installFromFile = ""
installInstructions = [
  "apt-get install -y docker-ce"
]
updateRepo = [
  "apt-get -y update",
  "apt-get install -y apt-transport-https ca-certificates curl software-properties-common",
  "curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -",
  "add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/debian jessie stable'",
  "apt-get -y update"
]

[[packages]]
name = "kubernetes"
version = "1.9.3-00"
checkInstalledCmd = [
  "which kubelet"
]
installFromFile = ""
installInstructions = [
  "kubePkgs='kubeadm kubectl kubelet'",
  "echo $kubePkgs",
  "apt-get install -y $kubePkgs",
  "swapoff -a",
  "kubeadm init",
  "mkdir -p $HOME/.kube",
  "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config",
  "chown $(id -u):$(id -g) $HOME/.kube/config",
  "KUBE_VER=$(kubectl version | base64 | tr -d '\n') && kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=${KUBE_VER}",
  "kubectl taint nodes --all node-role.kubernetes.io/master-"
]
updateRepo = [
  "apt-get -y update",
  "apt-get -y install git curl apt-transport-https",
  "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -",
  "add-apt-repository 'deb http://apt.kubernetes.io/ kubernetes-xenial main'",
  "apt-get -y update"
]
